name: Update YouTube Videos  
on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch Latest YouTube Videos
        uses: gautamkrishnar/blog-post-workflow@1.7.4
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCu1QanwX4FznnyAVJxCfv6g"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated YouTube videos" || echo "No changes to commit"
          git push
